# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Plan Maths 974
masthead_title: "Plans Maths 974"
subtitle: "Cycle 3 & 4"
name: "Florian Tobé"
email: florian.tobe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Un site pour bosser les maths Cycle 4 en autonomie 
  avec des plans de travail et une trace écrite 
  minimale pour retenir ce qu'il y a de bons à savoir.
baseurl: "/matmatik974.org" # the subpath of your site, e.g. /blog
url: "rodeofly.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: florian.tobe
github_username:  rodeofly
repository: "rodeofly/matmatik974.org"
locale : fr

  
logo: "/assets/images/dodo.fini.png"
breadcrumbs: true
include: ["_pages"]
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins:
  - jekyll-include-cache
 
minimal_mistakes_skin: aqua #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


teaser: /assets/images/blog/leçon.png


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
